### ISSUE TITLE
Link to google group on front page

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s-developer#3]

**Comment by zerocrates** [comment]
Wasn't there a tentative decision a while ago to kind of separate S stuff from the list? Instead favoring a section of the forums?

**Comment by sharonmleon** [comment]
Yes. This is my understanding too. That's why I pulled it from the support list on the launch page draft.

**Comment by patrickmj** [comment]
I must've remembered wrongly, then. Thought that we were still good with Omeka S stuff coming in the dev list.
