### ISSUE TITLE
Module DB updates ignore possibility of multiple updates present

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s-developer#5]
If you are out of date, the suggested path to how to do updates ignores that multiple modules, and indeed core, could give SQL update instruction when running the update sql tool. 

We'll need to give guidance about parsing that out for what a developer needs to pay attention to.

**Comment by zerocrates** [comment]
No longer a problem with the newer module db data script, which only emits SQL for the module you ask it about.
