### ISSUE TITLE
Proposed docs reorganization

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s-developer#55]
The [reorganization](https://github.com/omeka/omeka-s-developer/tree/reorganization) branch is an attempt to reorganize the docs in a more logical and intuitive fashion. This breaks internal links, but mkdocs can help us find and correct them. This also breaks the flow of some of the content, which we'll need to correct by proofing each page to fit into the new structure. We'll eventually have to change the order of the navigation, but that will have to wait until we finish organization.

But before I continue I need some eyes on the new organization. Does it make sense from a developer's perspective? A module developer? A theme developer?

```
- Omeka S Developer Documentation
- Contributing to Omeka S
- Debugging Omeka S
- For Omeka Classic Developers
- Registering an Addon
- Api
    - Introduction to the API
    - API Reference
    - REST API
- Configuration
    - Configuring Omeka S
    - Configuration Reference
    - Services and Factories
- Controllers
    - Introduction to Controllers
    - Controller Plugins
    - Routes and Navigation
    - ViewModel
- Events
    - Client Event Reference
    - Client Events
    - Server Event Reference
    - Server Events
- Miscellaneous
    - Access Control Lists (ACL)
    - Doctrine ORM
    - Forms
    - Internationalization
- Modules
    - Introduction to Modules
    - Data Model
    - Data Types
    - Media Ingesters and Renderers
    - Page Blocks
- Themes
    - Introduction to Themes
    - Sass and CSS
    - Style Guide
    - Theme Modifications
    - Theme Settings
- Views
    - Introduction to Views
    - Representations
    - View Helpers
```
There are some new pages that need content:

- "Introduction to the API": an introduction to the API and documentation for the programmatic API
- "API Reference": a reference for search criteria and request options
- "Introduction to Controllers": an introduction to controllers
- "Controller Plugins": a list of controller plugins and how to create one
- "Introduction to Views": an introduction to views

@zerocrates This is a slight departure from where we left off yesterday. I've added back in the "Modules" section because "Themes" is a separate section and the contents of the (now deleted) "Extending" section are specific to modules. I moved the "Introduction to..." pages to their respective "Modules" and "Themes" sections. Also, I'm particularly interested in getting your help editing the page content to fit into the new "flow" that the organization imposes. I don't have the time to do this alone.

**Comment by zerocrates** [comment]
I'm not sure what kind of editing we're talking about here, obviously there was pretty much _no_ "flow" among sections before... in terms of flow it seems to me like we would want more or less "front page" type content to try to direct people to what might be an appropriate area.

But, dealing with the pages we have now, it seems to me like we're talking about pretty simple linkage from pages to the corresponding reference pages, that kind of thing. Almost more of link repair than anything else.

Or is just that what you're talking about?
