### ISSUE TITLE
API Parameter Defaults

### ISSUE THREAD

**Issue by triplingual** [omeka/omeka-s-developer#56]
As with [API Request Options](https://omeka.org/s/docs/developer/api/api_reference/#api-request-options), [API Search Parameters] should have a defaults column.

**Comment by zerocrates** [comment]
There's (now) defaults for the "basic" shared stuff listed, and in general those are the only ones that would have defaults.

Obviously this is a pretty old issue, feel free to reply/refile if something is still not addressed.
