### ISSUE TITLE
Event guidance on migration

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s-developer#6]
Currently, we guide toward the SQL statements for updating/migrating. But I don't immediately see where/how to invoke the event. That should be more prominent.

Also notable, the current docs are `ant`-based, which seems to be going the way of the dodo

**Comment by zerocrates** [comment]
What does "how to invoke the event" mean in this context?

**Comment by patrickmj** [comment]
Meant what function to put it in, which is fixed in your additions.
