### ISSUE TITLE
media field with language attribute

### ISSUE THREAD

**Issue by ronniebrito** [omeka/omeka-s-developer#61]
hi there, 

we are using omeka s in our library and a requirement for uploaded files (or URLs) appeared.

in order to show the right file version for the user, after he chooses the front end language, we need to catalog the file/URL language

curent field types dont allow this metadata to be inserted, so, would ther be any plugin to fulffill this requisit?

if not, what part of omeka source code need to be changed to allow this aditional descriptio for uploaded files

thanks!

**Comment by zerocrates** [comment]
We didn't really catch this issue: this is the repository for the developer documentation, not Omeka S itself.

We've since added the ability to set the language for Media to Omeka S, though.
